install.packages('shiny', repos = "https://cran.wu.ac.at")
install.packages('shinyBS', repos = "https://cran.wu.ac.at")
install.packages('ggplot2', repos = "https://cran.wu.ac.at")
install.packages('plotly', repos = "https://cran.wu.ac.at")
install.packages('RColorBrewer', repos = "https://cran.wu.ac.at")
install.packages('heatmaply', repos = "https://cran.wu.ac.at")
install.packages('stringr', repos = "https://cran.wu.ac.at")
install.packages('BioCircos', repos = "https://cran.wu.ac.at")